[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#45475a"
blue = "#778da9"
cyan = "#9cc5a1"
green = "#a3d6a9"
magenta = "#364156"
red = "#d66853"
white = "#fdfdff"
yellow = "#e0af68"

[colors.normal]
black = "#45475a"
blue = "#778da9"
cyan = "#9cc5a1"
green = "#a3d6a9"
magenta = "#364156"
red = "#d66853"
white = "#fdfdff"
yellow = "#e0af68"


[selection]
save_to_clipboard = true
#mouse_bindings = { mouse: Right, action: Paste }


[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[cursor]
style = "Beam"
unfocused_hollow = false



[colors.primary]
background = "#121212"
foreground = "#f4f4f9"


[font]
size = 12



[font.glyph_offset]
x = 0
y = 0


[mouse]
hide_when_typing = false

[scrolling]
history = 2000
multiplier = 5

[window]
decorations = "none"
opacity = 0.75
startup_mode = "Windowed"
dynamic_padding = false

[window.dimensions]
columns = 0
lines = 0


[window.padding]
x = 5
y = 5


